# Generated by Django 4.1.4 on 2023-09-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produk',
            old_name='kategori',
            new_name='kategori_id',
        ),
        migrations.RenameField(
            model_name='produk',
            old_name='status',
            new_name='status_id',
        ),
    ]
